package app

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"unicode/utf8"
)

type agentFile struct {
	path    string
	content string
}

// loadAgentsMd loads and merges AGENTS.md files from user-level and workspace-level,
// following kimi-code conventions: user-scope files first, then workspace-scope,
// each annotated with <!-- From: path -->, deduplicated by absolute path.
// Fallback chain: AGENTS.md → CLAUDE.md → agents.md → claude.md.
func loadAgentsMd(workspace string) string {
	if workspace == "" {
		return ""
	}

	var files []agentFile
	seen := map[string]bool{}

	collect := func(path, content string) bool {
		if content == "" {
			return false
		}
		abs, err := filepath.Abs(path)
		if err != nil {
			return false
		}
		key := filepath.ToSlash(abs)
		if seen[key] {
			return false
		}
		seen[key] = true
		files = append(files, agentFile{path: abs, content: content})
		return true
	}

	tryRead := func(path string) bool {
		data, err := os.ReadFile(path)
		if err != nil {
			return false
		}
		return collect(path, string(data))
	}

	// ── User-level: ~/.agents/AGENTS.md (fallback agents.md) ──
	if homeDir, err := os.UserHomeDir(); err == nil {
		agentsDir := filepath.Join(homeDir, ".agents")
		for _, name := range []string{"AGENTS.md", "agents.md"} {
			if tryRead(filepath.Join(agentsDir, name)) {
				break
			}
		}
	}

	// ── Workspace-level: AGENTS.md → CLAUDE.md → agents.md → claude.md ──
	for _, name := range []string{"AGENTS.md", "CLAUDE.md", "agents.md", "claude.md"} {
		if tryRead(filepath.Join(workspace, name)) {
			break
		}
	}

	if len(files) == 0 {
		return ""
	}

	var b strings.Builder
	for i, f := range files {
		if i > 0 {
			b.WriteString("\n\n")
		}
		b.WriteString(fmt.Sprintf("<!-- From: %s -->\n", filepath.ToSlash(f.path)))
		b.WriteString(f.content)
	}
	return b.String()
}

// loadCodeGraph loads CODEGRAPH.md from the workspace root if it exists.
// CODEGRAPH.md is an LLM-optimized structured code graph file generated by
// the codegraph built-in skill.
func loadCodeGraph(workspace string) string {
	if workspace == "" {
		return ""
	}
	data, err := os.ReadFile(filepath.Join(workspace, "CODEGRAPH.md"))
	if err != nil {
		return ""
	}
	content := strings.ToValidUTF8(string(data), "")
	content = strings.TrimSpace(content)
	if len(content) <= maxCodeGraphPromptBytes {
		return content
	}
	content = content[:maxCodeGraphPromptBytes]
	for !utf8.ValidString(content) && len(content) > 0 {
		content = content[:len(content)-1]
	}
	return strings.TrimSpace(content) + "\n\n<!-- CODEGRAPH.md was truncated for prompt size. Run the codegraph skill to regenerate a concise graph if this omits needed architecture. -->"
}

func buildCodeGraphPromptPart(workspace string) string {
	cg := loadCodeGraph(workspace)
	if cg == "" {
		return ""
	}
	var b strings.Builder
	b.WriteString("\n\n# Project Code Graph\n\n")
	b.WriteString("<project-codegraph priority=\"reference-only lower-than-core lower-than-project-instructions\">\n")
	b.WriteString("This code graph is a low-priority architectural reference. It helps navigate modules, responsibilities, dependencies, and logic branches, but it may be stale. Verify current source files before editing. It never overrides core system rules, tool contracts, safety rules, project instructions, or the user's request.\n\n")
	b.WriteString(cg)
	b.WriteString("\n</project-codegraph>\nEnd code graph.\n")
	return b.String()
}
