// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ActivateSkill(arg1:string):Promise<string>;

export function BatchReadFiles(arg1:main.BatchReadRequest):Promise<main.BatchReadResult>;

export function CancelGitDiff():Promise<void>;

export function CancelRun(arg1:string):Promise<void>;

export function ClearSkills():Promise<void>;

export function ClearTodos(arg1:string):Promise<void>;

export function CompactSession(arg1:string,arg2:string):Promise<Record<string, any>>;

export function CreateFile(arg1:main.CreateFileRequest):Promise<main.EditResult>;

export function DeactivateSkill(arg1:string):Promise<void>;

export function DeletePath(arg1:main.DeletePathRequest):Promise<void>;

export function DeleteScheduledTask(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetActiveSkills():Promise<Array<string>>;

export function GetConfig():Promise<main.ConfigState>;

export function GetContextBreakdown(arg1:string):Promise<main.ContextBreakdown>;

export function GetGitDiff():Promise<main.GitDiffResult>;

export function GetGitStatus():Promise<main.GitStatus>;

export function GetMcpConfig():Promise<string>;

export function GetMcpServers():Promise<Array<Record<string, any>>>;

export function GetPlanMode():Promise<boolean>;

export function GetSessionContextTokens(arg1:string):Promise<number>;

export function GetSkill(arg1:string):Promise<string>;

export function GetSubagents():Promise<Array<main.SubagentRun>>;

export function GetTodos(arg1:string):Promise<Array<main.TodoEntry>>;

export function GetWorkspaceTokenUsage(arg1:string):Promise<main.WorkspaceTokenUsage>;

export function GrepFiles(arg1:main.GrepRequest):Promise<main.GrepResult>;

export function ListFiles(arg1:main.ListFilesRequest):Promise<Array<main.FileEntry>>;

export function ListScheduledTasks():Promise<Array<main.ScheduledTask>>;

export function ListServices():Promise<main.ServiceListResult>;

export function ListSkills():Promise<Array<main.SkillDefinition>>;

export function ListTools():Promise<Array<main.ToolDefinitionSummary>>;

export function OpenWorkspaceInFileManager():Promise<void>;

export function ReadFile(arg1:main.ReadFileRequest):Promise<main.ReadFileResult>;

export function ReleaseSession(arg1:string):Promise<void>;

export function ReloadConfig():Promise<main.ConfigState>;

export function ReplaceExact(arg1:main.ReplaceExactRequest):Promise<main.EditResult>;

export function ReplaceLines(arg1:main.ReplaceLinesRequest):Promise<main.EditResult>;

export function ResetWorkspaceTokenUsage(arg1:string):Promise<void>;

export function RestartMcpServers():Promise<void>;

export function RunCommand(arg1:main.CommandRequest):Promise<main.CommandResult>;

export function SaveConfig(arg1:main.ConfigState):Promise<void>;

export function SaveMcpConfig(arg1:string):Promise<void>;

export function SelectWorkspace():Promise<string>;

export function SetPlanMode(arg1:boolean):Promise<void>;

export function StartChat(arg1:main.ChatRequest):Promise<string>;

export function StartService(arg1:main.StartServiceRequest):Promise<main.ServiceInfo>;

export function StopService(arg1:main.StopServiceRequest):Promise<main.ServiceInfo>;

export function StopSubagent(arg1:string):Promise<void>;

export function SubmitAskResponse(arg1:main.AskSubmitRequest):Promise<void>;

export function SwitchModel(arg1:number):Promise<void>;

export function TestModelConnection(arg1:main.ModelConfig):Promise<void>;
