// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateSkill(arg1) {
  return window['go']['main']['App']['ActivateSkill'](arg1);
}

export function BatchReadFiles(arg1) {
  return window['go']['main']['App']['BatchReadFiles'](arg1);
}

export function CancelGitDiff() {
  return window['go']['main']['App']['CancelGitDiff']();
}

export function CancelRun(arg1) {
  return window['go']['main']['App']['CancelRun'](arg1);
}

export function ClearSkills() {
  return window['go']['main']['App']['ClearSkills']();
}

export function ClearTodos(arg1) {
  return window['go']['main']['App']['ClearTodos'](arg1);
}

export function CompactSession(arg1, arg2) {
  return window['go']['main']['App']['CompactSession'](arg1, arg2);
}

export function CreateFile(arg1) {
  return window['go']['main']['App']['CreateFile'](arg1);
}

export function DeactivateSkill(arg1) {
  return window['go']['main']['App']['DeactivateSkill'](arg1);
}

export function DeletePath(arg1) {
  return window['go']['main']['App']['DeletePath'](arg1);
}

export function DeleteScheduledTask(arg1) {
  return window['go']['main']['App']['DeleteScheduledTask'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DetectSystemProxy() {
  return window['go']['main']['App']['DetectSystemProxy']();
}

export function GetActiveSkills() {
  return window['go']['main']['App']['GetActiveSkills']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetContextBreakdown(arg1) {
  return window['go']['main']['App']['GetContextBreakdown'](arg1);
}

export function GetGitDiff() {
  return window['go']['main']['App']['GetGitDiff']();
}

export function GetGitStatus() {
  return window['go']['main']['App']['GetGitStatus']();
}

export function GetGoal(arg1) {
  return window['go']['main']['App']['GetGoal'](arg1);
}

export function GetMcpConfig() {
  return window['go']['main']['App']['GetMcpConfig']();
}

export function GetMcpServers() {
  return window['go']['main']['App']['GetMcpServers']();
}

export function GetServiceOutput(arg1) {
  return window['go']['main']['App']['GetServiceOutput'](arg1);
}

export function GetSessionContextTokens(arg1) {
  return window['go']['main']['App']['GetSessionContextTokens'](arg1);
}

export function GetSkill(arg1) {
  return window['go']['main']['App']['GetSkill'](arg1);
}

export function GetSubagents() {
  return window['go']['main']['App']['GetSubagents']();
}

export function GetTodos(arg1) {
  return window['go']['main']['App']['GetTodos'](arg1);
}

export function GetWorkspaceTokenUsage(arg1) {
  return window['go']['main']['App']['GetWorkspaceTokenUsage'](arg1);
}

export function GrepFiles(arg1) {
  return window['go']['main']['App']['GrepFiles'](arg1);
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function ListScheduledTasks() {
  return window['go']['main']['App']['ListScheduledTasks']();
}

export function ListServices() {
  return window['go']['main']['App']['ListServices']();
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function ListTools() {
  return window['go']['main']['App']['ListTools']();
}

export function OpenPathInFileManager(arg1) {
  return window['go']['main']['App']['OpenPathInFileManager'](arg1);
}

export function OpenWorkspaceInFileManager() {
  return window['go']['main']['App']['OpenWorkspaceInFileManager']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReleaseSession(arg1) {
  return window['go']['main']['App']['ReleaseSession'](arg1);
}

export function ReloadConfig() {
  return window['go']['main']['App']['ReloadConfig']();
}

export function ReplaceExact(arg1) {
  return window['go']['main']['App']['ReplaceExact'](arg1);
}

export function ReplaceLines(arg1) {
  return window['go']['main']['App']['ReplaceLines'](arg1);
}

export function ResetWorkspaceTokenUsage(arg1) {
  return window['go']['main']['App']['ResetWorkspaceTokenUsage'](arg1);
}

export function RestartMcpServers() {
  return window['go']['main']['App']['RestartMcpServers']();
}

export function RunCommand(arg1) {
  return window['go']['main']['App']['RunCommand'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveMcpConfig(arg1) {
  return window['go']['main']['App']['SaveMcpConfig'](arg1);
}

export function SelectWorkspace() {
  return window['go']['main']['App']['SelectWorkspace']();
}

export function StartChat(arg1) {
  return window['go']['main']['App']['StartChat'](arg1);
}

export function StartService(arg1) {
  return window['go']['main']['App']['StartService'](arg1);
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}

export function StopSubagent(arg1) {
  return window['go']['main']['App']['StopSubagent'](arg1);
}

export function SubmitAskResponse(arg1) {
  return window['go']['main']['App']['SubmitAskResponse'](arg1);
}

export function SwitchModel(arg1) {
  return window['go']['main']['App']['SwitchModel'](arg1);
}

export function TestModelConnection(arg1) {
  return window['go']['main']['App']['TestModelConnection'](arg1);
}

export function TestProxy(arg1) {
  return window['go']['main']['App']['TestProxy'](arg1);
}
